 const details = [
    {
      key: 1,
      firstName: 'abin',
      lastName: 'toppo',
      department: 'finance',
      salary: 100000,
    },
    {
        key: 2,
        firstName: 'aarif',
        lastName: 'raja',
        department: 'maintenance',
        salary: 30000,
      },{
        key: 3,
        firstName: 'warish',
        lastName: 'hasmi',
        department: 'production',
        salary: 40000,
      },
      {
        key: 4,
        firstName: 'loky',
        lastName: 'hasmi',
        department: 'production',
        salary: 40000,
      },{
        key: 5,
        firstName: 'sri',
        lastName: 'thakur',
        department: 'production',
        salary: 40000,
      },{
        key: 6,
        firstName: 'lucky',
        lastName: 'singh',
        department: 'finance',
        salary: 70000,
      },{
        key: 7,
        firstName: 'warish',
        lastName: 'hasmi',
        department: 'production',
        salary: 40000,
      },{
        key: 8,
        firstName: 'sahil',
        lastName: 'hasmi',
        department: 'production',
        salary: 50000,
      },{
        key: 9,
        firstName: 'hasan',
        lastName: 'hasmi',
        department: 'finance',
        salary: 40000,
      },{
        key: 10,
        firstName: 'warish',
        lastName: 'hasmi',
        department: 'production',
        salary: 40000,
      },{
        key: 11,
        firstName: 'rakesh',
        lastName: 'tiwari',
        department: 'legal',
        salary: 60000,
      },{
        key: 12,
        firstName: 'vikash',
        lastName: 'dubey',
        department: 'production',
        salary: 40000,
      },{
        key: 13,
        firstName: 'elvish',
        lastName: 'yadav',
        department: 'finance',
        salary: 70000,
      },{
        key: 14,
        firstName: 'boby',
        lastName: 'deol',
        department: 'legal',
        salary: 45000,
      },{
        key: 15,
        firstName: 'harshit',
        lastName: 'srivastav',
        department: 'production',
        salary: 35000,
      },{
        key: 16,
        firstName: 'shivam',
        lastName: 'tiwari',
        department: 'legal',
        salary: 70000,
      },{
        key: 17,
        firstName: 'ahasan',
        lastName: 'alam',
        department: 'maintenance',
        salary: 30000,
      },{
        key: 18,
        firstName: 'pervin',
        lastName: 'bundela',
        department: 'finance',
        salary: 60000,
      },{
        key: 19,
        firstName: 'ritesh',
        lastName: 'desmukh',
        department: 'legal',
        salary: 40000,
      },{
        key: 20,
        firstName: 'ruksar',
        lastName: 'bano',
        department: 'finance',
        salary: 70000,
      },
      {
        key: 21,
        firstName: 'abin',
        lastName: 'toppo',
        department: 'finance',
        salary: 100000,
      },
      {
          key: 22,
          firstName: 'aarif',
          lastName: 'raja',
          department: 'maintenance',
          salary: 30000,
        },{
          key: 23,
          firstName: 'warish',
          lastName: 'hasmi',
          department: 'production',
          salary: 40000,
        },
        {
          key: 24,
          firstName: 'loky',
          lastName: 'hasmi',
          department: 'production',
          salary: 40000,
        },{
          key: 25,
          firstName: 'sri',
          lastName: 'thakur',
          department: 'production',
          salary: 40000,
        },{
          key: 26,
          firstName: 'lucky',
          lastName: 'singh',
          department: 'finance',
          salary: 70000,
        },{
          key: 27,
          firstName: 'warish',
          lastName: 'hasmi',
          department: 'production',
          salary: 40000,
        },{
          key: 28,
          firstName: 'sahil',
          lastName: 'hasmi',
          department: 'production',
          salary: 50000,
        },{
          key: 29,
          firstName: 'hasan',
          lastName: 'hasmi',
          department: 'finance',
          salary: 40000,
        },{
          key: 30,
          firstName: 'warish',
          lastName: 'hasmi',
          department: 'production',
          salary: 40000,
        },{
          key: 31,
          firstName: 'rakesh',
          lastName: 'tiwari',
          department: 'legal',
          salary: 60000,
        },{
          key: 32,
          firstName: 'vikash',
          lastName: 'dubey',
          department: 'production',
          salary: 40000,
        },{
          key: 33,
          firstName: 'elvish',
          lastName: 'yadav',
          department: 'finance',
          salary: 70000,
        },{
          key: 34,
          firstName: 'boby',
          lastName: 'deol',
          department: 'legal',
          salary: 45000,
        },{
          key: 35,
          firstName: 'harshit',
          lastName: 'srivastav',
          department: 'production',
          salary: 35000,
        },{
          key: 36,
          firstName: 'shivam',
          lastName: 'tiwari',
          department: 'legal',
          salary: 70000,
        },{
          key: 37,
          firstName: 'ahasan',
          lastName: 'alam',
          department: 'maintenance',
          salary: 30000,
        },{
          key: 38,
          firstName: 'pervin',
          lastName: 'bundela',
          department: 'finance',
          salary: 60000,
        },{
          key: 39,
          firstName: 'ritesh',
          lastName: 'desmukh',
          department: 'legal',
          salary: 40000,
        },{
          key: 40,
          firstName: 'ruksar',
          lastName: 'bano',
          department: 'finance',
          salary: 70000,
        },
        {
            key: 41,
            firstName: 'abin',
            lastName: 'toppo',
            department: 'finance',
            salary: 100000,
          },
          {
              key: 42,
              firstName: 'aarif',
              lastName: 'raja',
              department: 'maintenance',
              salary: 30000,
            },{
              key: 43,
              firstName: 'warish',
              lastName: 'hasmi',
              department: 'production',
              salary: 40000,
            },
            {
              key: 44,
              firstName: 'loky',
              lastName: 'hasmi',
              department: 'production',
              salary: 40000,
            },{
              key: 45,
              firstName: 'sri',
              lastName: 'thakur',
              department: 'production',
              salary: 40000,
            },{
              key: 46,
              firstName: 'lucky',
              lastName: 'singh',
              department: 'finance',
              salary: 70000,
            },{
              key: 47,
              firstName: 'warish',
              lastName: 'hasmi',
              department: 'production',
              salary: 40000,
            },{
              key: 48,
              firstName: 'sahil',
              lastName: 'hasmi',
              department: 'production',
              salary: 50000,
            },{
              key: 49,
              firstName: 'hasan',
              lastName: 'hasmi',
              department: 'finance',
              salary: 40000,
            },{
              key: 50,
              firstName: 'warish',
              lastName: 'hasmi',
              department: 'production',
              salary: 40000,
            },{
              key: 51,
              firstName: 'rakesh',
              lastName: 'tiwari',
              department: 'legal',
              salary: 60000,
            },{
              key: 52,
              firstName: 'vikash',
              lastName: 'dubey',
              department: 'production',
              salary: 40000,
            },{
              key: 53,
              firstName: 'elvish',
              lastName: 'yadav',
              department: 'finance',
              salary: 70000,
            },{
              key: 54,
              firstName: 'boby',
              lastName: 'deol',
              department: 'legal',
              salary: 45000,
            },{
              key: 55,
              firstName: 'harshit',
              lastName: 'srivastav',
              department: 'production',
              salary: 35000,
            },{
              key: 56,
              firstName: 'shivam',
              lastName: 'tiwari',
              department: 'legal',
              salary: 70000,
            },{
              key: 57,
              firstName: 'ahasan',
              lastName: 'alam',
              department: 'maintenance',
              salary: 30000,
            },{
              key: 58,
              firstName: 'pervin',
              lastName: 'bundela',
              department: 'finance',
              salary: 60000,
            },{
              key: 59,
              firstName: 'ritesh',
              lastName: 'desmukh',
              department: 'legal',
              salary: 40000,
            },{
              key: 60,
              firstName: 'ruksar',
              lastName: 'bano',
              department: 'finance',
              salary: 70000,
            },
            {
                key: 61,
                firstName: 'abin',
                lastName: 'toppo',
                department: 'finance',
                salary: 100000,
              },
              {
                  key: 62,
                  firstName: 'aarif',
                  lastName: 'raja',
                  department: 'maintenance',
                  salary: 30000,
                },{
                  key: 63,
                  firstName: 'warish',
                  lastName: 'hasmi',
                  department: 'production',
                  salary: 40000,
                },
                {
                  key: 64,
                  firstName: 'loky',
                  lastName: 'hasmi',
                  department: 'production',
                  salary: 40000,
                },{
                  key: 65,
                  firstName: 'sri',
                  lastName: 'thakur',
                  department: 'production',
                  salary: 40000,
                },{
                  key: 66,
                  firstName: 'lucky',
                  lastName: 'singh',
                  department: 'finance',
                  salary: 70000,
                },{
                  key: 67,
                  firstName: 'warish',
                  lastName: 'hasmi',
                  department: 'production',
                  salary: 40000,
                },{
                  key: 68,
                  firstName: 'sahil',
                  lastName: 'hasmi',
                  department: 'production',
                  salary: 50000,
                },{
                  key: 69,
                  firstName: 'hasan',
                  lastName: 'hasmi',
                  department: 'finance',
                  salary: 40000,
                },{
                  key: 70,
                  firstName: 'warish',
                  lastName: 'hasmi',
                  department: 'production',
                  salary: 40000,
                },{
                  key: 71,
                  firstName: 'rakesh',
                  lastName: 'tiwari',
                  department: 'legal',
                  salary: 60000,
                },{
                  key: 72,
                  firstName: 'vikash',
                  lastName: 'dubey',
                  department: 'production',
                  salary: 40000,
                },{
                  key: 73,
                  firstName: 'elvish',
                  lastName: 'yadav',
                  department: 'finance',
                  salary: 70000,
                },{
                  key: 74,
                  firstName: 'boby',
                  lastName: 'deol',
                  department: 'legal',
                  salary: 45000,
                },{
                  key: 75,
                  firstName: 'harshit',
                  lastName: 'srivastav',
                  department: 'production',
                  salary: 35000,
                },{
                  key: 76,
                  firstName: 'shivam',
                  lastName: 'tiwari',
                  department: 'legal',
                  salary: 70000,
                },{
                  key: 77,
                  firstName: 'ahasan',
                  lastName: 'alam',
                  department: 'maintenance',
                  salary: 30000,
                },{
                  key: 78,
                  firstName: 'pervin',
                  lastName: 'bundela',
                  department: 'finance',
                  salary: 60000,
                },{
                  key: 79,
                  firstName: 'ritesh',
                  lastName: 'desmukh',
                  department: 'legal',
                  salary: 40000,
                },{
                  key: 80,
                  firstName: 'ruksar',
                  lastName: 'bano',
                  department: 'finance',
                  salary: 70000,
                },
                {
                    key: 81,
                    firstName: 'abin',
                    lastName: 'toppo',
                    department: 'finance',
                    salary: 100000,
                  },
                  {
                      key: 82,
                      firstName: 'aarif',
                      lastName: 'raja',
                      department: 'maintenance',
                      salary: 30000,
                    },{
                      key: 83,
                      firstName: 'warish',
                      lastName: 'hasmi',
                      department: 'production',
                      salary: 40000,
                    },
                    {
                      key: 84,
                      firstName: 'loky',
                      lastName: 'hasmi',
                      department: 'production',
                      salary: 40000,
                    },{
                      key: 85,
                      firstName: 'sri',
                      lastName: 'thakur',
                      department: 'production',
                      salary: 40000,
                    },{
                      key: 86,
                      firstName: 'lucky',
                      lastName: 'singh',
                      department: 'finance',
                      salary: 70000,
                    },{
                      key: 87,
                      firstName: 'warish',
                      lastName: 'hasmi',
                      department: 'production',
                      salary: 40000,
                    },{
                      key: 88,
                      firstName: 'sahil',
                      lastName: 'hasmi',
                      department: 'production',
                      salary: 50000,
                    },{
                      key: 89,
                      firstName: 'hasan',
                      lastName: 'hasmi',
                      department: 'finance',
                      salary: 40000,
                    },{
                      key: 90,
                      firstName: 'warish',
                      lastName: 'hasmi',
                      department: 'production',
                      salary: 40000,
                    },{
                      key: 91,
                      firstName: 'rakesh',
                      lastName: 'tiwari',
                      department: 'legal',
                      salary: 60000,
                    },{
                      key: 92,
                      firstName: 'vikash',
                      lastName: 'dubey',
                      department: 'production',
                      salary: 40000,
                    },{
                      key: 93,
                      firstName: 'elvish',
                      lastName: 'yadav',
                      department: 'finance',
                      salary: 70000,
                    },{
                      key: 94,
                      firstName: 'boby',
                      lastName: 'deol',
                      department: 'legal',
                      salary: 45000,
                    },{
                      key: 95,
                      firstName: 'harshit',
                      lastName: 'srivastav',
                      department: 'production',
                      salary: 35000,
                    },{
                      key: 96,
                      firstName: 'shivam',
                      lastName: 'tiwari',
                      department: 'legal',
                      salary: 70000,
                    },{
                      key: 97,
                      firstName: 'ahasan',
                      lastName: 'alam',
                      department: 'maintenance',
                      salary: 30000,
                    },{
                      key: 98,
                      firstName: 'pervin',
                      lastName: 'bundela',
                      department: 'finance',
                      salary: 60000,
                    },{
                      key: 99,
                      firstName: 'ritesh',
                      lastName: 'desmukh',
                      department: 'legal',
                      salary: 40000,
                    },{
                      key: 100,
                      firstName: 'ruksar',
                      lastName: 'bano',
                      department: 'finance',
                      salary: 70000,
                    },
       ];

       export default details;